spring:
  datasource:
    url: jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL
    username: rm551236
    password: 171103
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
server:
  port: 998